name: moodify
description: "An application that recommends videos to you based on your daily mood."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.10.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^5.9.0

  # Cache
  shared_preferences: ^2.5.3
  hive_ce: ^2.15.0
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1

  # Loading
  shimmer: ^3.0.0

  # Core
  equatable: ^2.0.7
  kartal: ^4.2.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2

  # Localization
  easy_localization: ^3.0.7

  # Icon
  flutter_svg: ^2.2.3

  # Image
  image_picker: ^1.2.0

  # Toast
  fluttertoast: ^9.0.0

  # In App Purchases
  purchases_flutter: ^9.9.10

  # Json Serialization
  json_annotation: ^4.9.0

  # State Management
  provider: ^6.1.5+1

  # Deep Link
  app_links: ^6.4.1

  # Supabase
  supabase_flutter: ^2.10.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.6.1

  # Code Generator
  build_runner: ^2.10.3
  json_serializable: ^6.11.1
  hive_ce_generator: ^1.10.0

  # Linter
  very_good_analysis: ^10.0.0

  # App Icon
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-Bold.ttf
        - asset: assets/fonts/Epilogue-Medium.ttf
        - asset: assets/fonts/Epilogue-Regular.ttf
        - asset: assets/fonts/Epilogue-SemiBold.ttf
